/**
 * Generated by scripts/write-test-config.mjs for Tier B CI.
 * Do NOT commit this file — the workflow regenerates it per run.
 */
export const config = {
  apiBaseUrl: "http://10.0.2.2:8080",
  wsUrl: "ws://10.0.2.2:8080/ws",
  useMockSignalProtocol: true,
};
