/**
 * Client-side mirror of the server's PreKeyBundleInput. Concrete values are
 * generated by the Signal Protocol native module (Phase 2) and serialized as
 * base64 for the wire.
 */
export interface PreKey {
  id: number;
  /** base64 */
  key: string;
}

export interface PreKeyBundleInput {
  registrationId: number;
  signedPreKeyId: number;
  /** base64 */
  signedPreKey: string;
  /** base64 */
  signedPreKeySig: string;
  preKeys: PreKey[];
}
