import { describe, expect, it } from 'vitest';
import { xeddsaVerify } from './xeddsa.js';

/**
 * Ground-truth fixtures: real (identity public key, signed prekey,
 * signature) triples generated by production libsignal clients
 * (Android Curve.calculateSignature / iOS PrivateKey.generateSignature)
 * and read back from the prekey_bundles table on 2026-08-07. All three
 * values are public by design — this is exactly what
 * `/v1/prekeys/bundle` serves to any authenticated peer.
 */
const FIXTURES = [
  {
    pk: 'BQyCfgEvKB3rvazAhs4cDDDFoI28fs2brJyWDWqxjdAV',
    spk: 'BYVq28H5PLhjTPMMJ45LQAWAF/v82i4RfBLuKRt4x6th',
    sig: 'DJVrvCzrpbvpkECECmwN4OooHbTAPDS34EE9Rps87Fn8Y48llrTPe9sGg8qWxutDCLujA3sg4i6kzxDuAtVgjA==',
  },
  {
    pk: 'BQLeqASha0U5GOqd080pB5UOVGxAIiLYNz4lqvG73GYw',
    spk: 'BUA6kcTV/sv+UvICdsw+7ZprWKR444/SbAVCojCLEE9U',
    sig: '+lR0Il6tUxGHkn0JeYBNl4w5CJj2rj0sWpClUDsD1kt9ewXH+12pi6HKsBkMsAQ3qw9FT8Stj/vN+agMKwiuBw==',
  },
  {
    pk: 'BXINAEmfMcvd/DuNOdDKRWpkJOrHFS4bJ4UCsqxwwSYv',
    spk: 'BbROk6gO1WUV7ZKFCczSQ0Iw9xxS46RRLAFF12gUC4Nm',
    sig: 'hpf90PvOR1RTUEjNAmjkZARHd9ExmNbzafee3SqAhLt06iAzJ90Gm0E+qy6aMzpK3X4T/p+r+QzNG/cZD/5ihQ==',
  },
] as const;

const b64 = (s: string) => Uint8Array.from(Buffer.from(s, 'base64'));

describe('xeddsaVerify', () => {
  it('accepts all real client-generated signatures', () => {
    for (const f of FIXTURES) {
      expect(xeddsaVerify(b64(f.pk), b64(f.spk), b64(f.sig))).toBe(true);
    }
  });

  it('accepts a raw 32-byte (unprefixed) identity key', () => {
    const f = FIXTURES[0];
    expect(xeddsaVerify(b64(f.pk).subarray(1), b64(f.spk), b64(f.sig))).toBe(true);
  });

  it('rejects a signature over a different message', () => {
    // Sign from fixture 0, message from fixture 1.
    expect(
      xeddsaVerify(b64(FIXTURES[0].pk), b64(FIXTURES[1].spk), b64(FIXTURES[0].sig)),
    ).toBe(false);
  });

  it('rejects a signature by a different identity — the replay that matters', () => {
    // Fixture 1's valid bundle presented against fixture 0's on-file
    // identity: exactly the "new identity slots into old account" hole.
    expect(
      xeddsaVerify(b64(FIXTURES[0].pk), b64(FIXTURES[1].spk), b64(FIXTURES[1].sig)),
    ).toBe(false);
  });

  it('rejects a bit-flipped signature', () => {
    const f = FIXTURES[0];
    const sig = b64(f.sig);
    sig[10]! ^= 0x01;
    expect(xeddsaVerify(b64(f.pk), b64(f.spk), sig)).toBe(false);
  });

  it('rejects a bit-flipped message', () => {
    const f = FIXTURES[0];
    const msg = b64(f.spk);
    msg[20]! ^= 0x01;
    expect(xeddsaVerify(b64(f.pk), msg, b64(f.sig))).toBe(false);
  });

  it('rejects malformed inputs without throwing', () => {
    const f = FIXTURES[0];
    expect(xeddsaVerify(new Uint8Array(0), b64(f.spk), b64(f.sig))).toBe(false);
    expect(xeddsaVerify(new Uint8Array(31), b64(f.spk), b64(f.sig))).toBe(false);
    expect(xeddsaVerify(b64(f.pk), b64(f.spk), new Uint8Array(63))).toBe(false);
    expect(xeddsaVerify(b64(f.pk), b64(f.spk), new Uint8Array(64))).toBe(false);
  });
});
